version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_sql2
      MYSQL_USER: bguntupalli
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - /Users/21bguntupalli/Data/dbdata:/var/lib/mysql
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: pma
#    links:
#      - db
#    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#    restart: always
#    ports:
#      - 8081:80
  myapi:
    image: bguntupalli/myapi
    container_name: myapi
    ports:
      - 8080:8080
      - 3306:6033
    depends_on:
      - db
#volumes:
#  dbdata: